name: emoji_selector
homepage: https://github.com/Alfaizkhan/flutter-emoji-selector
issue_tracker: https://github.com/Alfaizkhan/flutter-emoji-selector/issues
description: An Emoji picker component for Flutter with the latest set of emojis. The current version supports Emoji version 15.
repository: https://github.com/Alfaizkhan/flutter-emoji_selector
version: 0.0.6

environment:
  sdk: ">=2.17.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/emoji_selector/data/emoji.json
