name: emoji_selector
description: An Emoji picker component for Flutter with the latest set of emojis. The current version supports Emoji version 13.
repository: https://github.com/Alfaizkhan/flutter-emoji_selector
version: 0.0.2

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/emoji_selector/data/emoji.json
